language: python
python:
  - "3.6.10"      # current default Python on Travis CI
# command to install dependencies
os:
  - windows
  - linux
  - osx
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install .[testing]
# command to run tests
script: pytest --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 5957e797-d903-46a8-b062-493bfd81f349 # submit coverage
