language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - python3 setup.py install
# command to run tests
script: pytest
