language: python
python:
  - "3.6.10"      # current default Python on Travis CI
# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[testing]"
# command to run tests
script: pytest --cov=./
after_success:
  - codecov # submit coverage
